version: 0.0.{build}
os: Visual Studio 2015
configuration: Release
 
install:
- git submodule update --init --recursive

build:
  project: src\Giacomelli.Unity.EditorToolbox.sln
  verbosity: minimal

after_build:
- cmd: >-    
   .\tools\build-ci.cmd
   
artifacts:
  - path: .\build\Giacomelli.Unity.EditorToolbox.dll
    name: Giacomelli.Unity.EditorToolbox.dll